### ISSUE TITLE
EEGLAB won't open - maximum recursion error

### ISSUE THREAD

**Issue by adabelsdsu** [eeglabdevelopers/eeglab#68] opened 2019-11-13 19:25 UTC
### Running Matlab 2018a and EEGLab v 14_1_2b. It used to work fine but now won't open. The error I get is that it cannot access the local eeg_options file and maximum recursion limit of 500 reached. I've uninstalled and re-installed both Matlab and EEGLab with the same result. Thoughts?

![image (1)](https://user-images.githubusercontent.com/57727698/68796647-16c90800-0608-11ea-9f55-9e446559c46f.png)

[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]
![image](https://user-images.githubusercontent.com/57727698/68796548-ec774a80-0607-11ea-851f-79c437619365.png)

<br>
#### Steps to Reproduce

1. [*First Step*]
2. [*Second Step*]
3. [*and so on...*]

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [*fill in*] |
| EEGLAB version | [*fill in*] |

**Comment by arnodelorme** [comment] 2019-11-28 20:25
Yes, it is a strange problem. My intuition is that either eeg_options.m or eeg_optionsbackup.m is corrupted. We would need to be able to set a breakpoint inside eeglab_options.m to figure out what the problem is.

You can try to go into the path and remove all non original Matlab paths.

Also under Matlab, you can type "which eeg_options.m" and delete the file.

Let us know,

Arno

**Comment by arnodelorme** [comment] 2019-12-11 02:56
And you can also update the EEGLAB 2019.1 (EEGLAB 14.2 is about 3 years old). Closing issue for now.

**Closed as completed by arnodelorme** 2019-12-11 02:56 UTC
Labels: question
