### ISSUE TITLE
Error while managing plugins

### ISSUE THREAD

**Issue by RodrigoHache** [eeglabdevelopers/eeglab#25] opened 2019-07-06 05:43 UTC
### Description
I was not able to load .mat files, I tried to manage the extensions in order to get more file extensions to load. I'm using the latest version, just cloned from git, and also I've just  included the sub-modules
<br>
#### Steps to Reproduce

1. Start EEGLab
2. Manage EEGLab extensions 
3. The error message pop-up: EEGLAB error in function plugin_menu()at line 41: attempts to reference field of non-structure arrays
<br>
#### Expected behavior:

<br>
#### Actual behavior:
Error pop-up window appeard 
<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Linux 5.1.15-arch1-1-ARCH |
| Matlab version | 2014b |
| EEGLAB version | |

**Comment by hosseinaghaie** [comment] 2019-07-15 18:16
![Untitled](https://user-images.githubusercontent.com/19975480/61238642-4fd49700-a752-11e9-92bd-85e3cf0aabee.png)

**Comment by hosseinaghaie** [comment] 2019-07-15 18:17
close your matlab
download 'jre-8u211-windows-x64.exe' ,and installed it
delete all file and folder in 'C:\Program Files\MATLAB\R2014b\sys\javal\jre\win64\jre'
copy all file of 'C:\Program Files\Java\jre1.8.0_211' in to 'C:\Program Files\MATLAB\R2014b\sys\javal\jre\win64\jre'

p.s: i install matlab and jre-8u211-windows-x64.exe in default folder,

![Untitled](https://user-images.githubusercontent.com/19975480/61238692-6c70cf00-a752-11e9-9edd-abebb7a8328b.png)

**Comment by nucleuscub** [comment] 2019-07-16 18:07
Thanks for addressing this issue, @hosseinaghaie. This is though, a duplicate of a currently closed issue. The issue will be flagged accordingly.
 Thanks,
R

**Closed as completed by nucleuscub** 2019-07-16 18:07 UTC
Labels: duplicate

**Comment by nucleuscub** [comment] 2019-07-16 18:08
See  [issue 20](https://github.com/sccn/eeglab/issues/20) for more information.
