### ISSUE TITLE
pop_runica() overwrites channel locations

### ISSUE THREAD

**Issue by ioalessandro** [eeglabdevelopers/eeglab#413] opened 2021-11-17 16:58 UTC
### Description

I am using the command line function `EEG = pop_runica(EEG, 'icatype', 'runica', 'extended',1,'interrupt','on');` to run ICA on my data that includes channel locations. After this command, the locations are gone, since the output of the function does not seem to include them and overwrites my EEG variable. How do I change this behaviour to merely adding the ica output structures to the EEG structure?

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [macOS] |
| Matlab version | [R2019b] |
| EEGLAB version | [2021.0] |

**Comment by cll008** [comment] 2021-11-18 18:56
`runica` shouldn't modify channel locations in any way, and I couldn't reproduce your problem. Are you sure the `EEG` you are inputting has channel locations?

- Is the EEG.chanlocs field missing entirely? 
- Which fields in the structure are empty?
- Are you looking at the GUI to determine 'Yes' or 'No' channel locations? If you use the command line you also have to type `eeglab redraw` to refresh the GUI

**Comment by ioalessandro** [comment] 2021-11-19 11:42
Thanks for getting back to me!

- The EEG.chanlocs field is present, yet empty after `runica`
- check out the attached screenshots for a pre/post `runica` comparison of `EEG `and the GUI
- I am, it reports the structures content correctly with `yes` pre ICA and `no` post ICA

<img width="846" alt="pre_ICA" src="https://user-images.githubusercontent.com/72192937/142617196-44f49e32-a21d-4846-bcac-4915c2d71650.png">

<img width="837" alt="post_ICA" src="https://user-images.githubusercontent.com/72192937/142617221-3f15405b-695b-4c3f-a52b-7808fef0ac00.png">

**Comment by cll008** [comment] 2021-11-22 18:13
Channel location says `yes` in the GUI for both images attached, but I see it's empty as you mentioned (in the variable explorer). I can't reproduce this problem though. Since you are mixing command line and GUI, it's possible there are some non-bug mistakes. 
Can you confirm `isempty(EEG.chanlocs)` immediately before you run `EEG = pop_runica(EEG, 'icatype', 'runica', 'extended',1,'interrupt','on')` and the same after?

**Comment by arnodelorme** [comment] 2021-11-23 01:27
Closing this for now, but feel free to reopen.

**Closed as completed by arnodelorme** 2021-11-23 01:27 UTC
