### ISSUE TITLE
ERPImage Study Error - processerpim at line 474

### ISSUE THREAD

**Issue by mplaweck** [eeglabdevelopers/eeglab#483] opened 2022-05-20 14:58 UTC
### Description
Created a simple study from a complicated dataset for testing and development - 1 subject with 2 sessions
Precompute study parameters without problem (ERP, Spectra, and ERPImage).
Plotting for ERP and Spectra works without Issue. 
Attempting to plot ERPimage produces the error 

EEGLAB error in function processerpim() at line 474
Output argument "outsort" (and maybe others) not assigned during call to "erpimage".

![bug](https://user-images.githubusercontent.com/94379267/169555234-0f73e3a1-762f-49c0-a5e9-bc885f65e254.jpg)

I have loaded the 1 subject 2 session dataset at 
https://drive.google.com/file/d/1RjXBw_GK2KRyEik8yBGpOIwB5zk2Tzc_/view?usp=sharing

To reproduce,
Load study, precompute study parameters and attempt to plot ERPimage

I am now running the developer Version 2022.1b, which solved a prior error with std_readfile with multi-session subjects

| OS version     | Win 11|
| Matlab version | R2021a |
| EEGLAB version | 2022.1b|

**Comment by arnodelorme** [comment] 2022-05-23 21:19
OK thank you. Will look into it.

**Comment by arnodelorme** [comment] 2022-05-25 02:41
Works for me, unfortunately. I have removed the annoying warning message about the parallel toolbox.

**Comment by arnodelorme** [comment] 2022-05-25 02:42
![Screen Shot 2022-05-24 at 7 41 13 PM](https://user-images.githubusercontent.com/1872705/170168394-bd9467e1-65c3-4de4-a650-3e951f24a10a.png)

**Comment by arnodelorme** [comment] 2022-05-25 02:48
- Loaded the study
- Precomputed ERPimage
- Plotted the first channel

Did the same with version 2022.0 on the web and it worked as well. Sorry I cannot help if I cannot reproduce the issue. Maybe you have a conflict between EEGLAB versions on your paths? Closing the report for now, but feel free to reopen if you think there is something else I can do.

**Closed as completed by arnodelorme** 2022-05-25 02:48 UTC

**Comment by mplaweck** [comment] 2022-05-31 14:34
I was able to replicate the issue, and it may result from my ignorance.
-Load the study
-Precompute study parameters, **but include the removal of prelabeled artifactual components**
-Attempt to plot the first channel

**Comment by mplaweck** [comment] 2022-05-31 14:37
Thank you for your attention to this matter
I was able to replicate the issue and put directions on the thread. Forgive me I this email is duplicative, but I am new to GitHub and both did not know how to “reopen” the issue nor is you would receive the updates to a closed issue.
Thanks
    Marty

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
