### ISSUE TITLE
Cannot adjust event latencies

### ISSUE THREAD

**Issue by Loluer** [eeglabdevelopers/eeglab#720] opened 2024-01-22 05:56 UTC
### Description

I am working with EGI.mff files and have imported event type fields, including the 'code' and 'mffkey'. I've encountered latency setting errors and need to adjust the event type latencies by -200ms.

However, I'm facing an issue in EEGLAB where, despite the event types being clearly displayed in both the event type options and the scrolled channel data, there seems to be a bug. Specifically, when trying to adjust latencies, EEGLAB reports that the requested event types are not found.

It's worth noting that I can successfully extract epochs using the same event types. I'm puzzled about why I cannot adjust latencies and would like guidance on how to debug this issue. Any insights or suggestions would be greatly appreciated.

<br>
#### Steps to Reproduce

1. import data
![step1](https://github.com/sccn/eeglab/assets/121941645/65ba304c-b6a0-4157-b146-1e638dcdecb6)

2. set the parameters to adjust latencies
![step2](https://github.com/sccn/eeglab/assets/121941645/d23b69fb-11d6-478d-b22d-04ce1890877d)
![step3](https://github.com/sccn/eeglab/assets/121941645/44feca96-3577-4e7d-8d97-2b65d435cc6d)

3. reported errors from EEGLAB
![step4](https://github.com/sccn/eeglab/assets/121941645/604c58e9-1693-4625-aab7-5dad67285f8b)
![step5](https://github.com/sccn/eeglab/assets/121941645/fc4f231f-ee1b-4581-94bb-99b0286b9380)

4. succeed to extract the epochs using same event types
 EEG = pop_epoch( EEG, {  'CSTI_p1s3'  'CSTI_p2s5'  'CSTI_p3s1'  'CSTI_p4s2'  'CSTI_p5s4'  'ISTI_p1s1'  'ISTI_p1s2'  'ISTI_p1s4'  'ISTI_p1s5'  'ISTI_p2s1'  'ISTI_p2s2'  'ISTI_p2s3'  'ISTI_p2s4'  'ISTI_p3s2'  'ISTI_p3s3'  'ISTI_p3s4'  'ISTI_p3s5'  'ISTI_p4s1'  'ISTI_p4s3'  'ISTI_p4s4'  'ISTI_p4s5'  'ISTI_p5s1'  'ISTI_p5s2'  'ISTI_p5s3'  'ISTI_p5s5'  }, [-1  2], 'newname', 'zhuyuntian_formal epochs', 'epochinfo', 'yes');

5. event types
![event type](https://github.com/sccn/eeglab/assets/121941645/c6541883-6cd5-4589-943f-687563fc6bc4)

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*windows 11*] |
| Matlab version | [*2021b*] |
| EEGLAB version | [*EEGLAB v2023.0*] |

**Comment by arnodelorme** [comment] 2024-02-08 04:19
Apologies for the late response. Cab you share a dataset so I can try. I cannot reproduce the problem.

**Comment by arnodelorme** [comment] 2024-02-09 02:07
I am closing this for now. Feel free to share a file and reopen the issue.

**Closed as completed by arnodelorme** 2024-02-09 02:07 UTC
