### ISSUE TITLE
PSD units when using the std_spec function in EEGLAB

### ISSUE THREAD

**Issue by esymeonidou** [eeglabdevelopers/eeglab#175] opened 2020-06-25 01:26 UTC
Hello, 

In Figure Cls 1(b) you can see a graph plotted with the **std_spec function with 'specmode,'psd','logtrials','off'** . Since the units seemed too small to me, I assumed that this was an error and they were actually supposed to be mV^2/Hz instead of μV^2/Hz - which EEGLAB defaults to when plotting PSD. 

To verify, I also plotted the spectral power using the erspdata collapsed across time, which was calculated with the **std_ersp function with 'baseline' NaN** (see Cls 1(a)). However, even if the values in Cls 1(b) are in mV^2/Hz, if I was to convert from the unnormalized units to dB (dB = 10*log10[X]) there would still be a discrepancy. Could somebody verify if the units on the right graph are in mV^2/Hz and if so, how can I convert them to match the values on the left graph?

Thanks a lot!
Eva

![2SpectraComparison](https://user-images.githubusercontent.com/38797245/85642518-c3b83880-b65f-11ea-91d5-8aa2ad3c015c.jpg)

**Comment by arnodelorme** [comment] 2020-07-06 03:04
Is it accurate to say that this is a duplicate of #172

**Closed as completed by arnodelorme** 2020-07-06 03:04 UTC
