### ISSUE TITLE
std_readdata error

### ISSUE THREAD

**Issue by CorentinWicht** [eeglabdevelopers/eeglab#198] opened 2020-08-20 06:55 UTC
### Description

Dear EEGLAB,

I am writting here to report a bug related to the std_readdata function (also in the GUI).

<br>
#### Steps to Reproduce

1. [*First Step*]
Load the [example study](https://www.dropbox.com/sh/tlkq03le7qp71oo/AAAA5oZ5q_VBX8a9K5sZRZXoa?dl=0)

2. [*Second Step*]
STUDY --> Precompute channel measures --> select only Power Spectrum with 'specmode', 'psd', 'logtrials', 'off' and untick the spherical interpolation (i.e. no influence on the error)

![image](https://user-images.githubusercontent.com/52161904/90725596-b8306900-e2c0-11ea-8b85-5fc0ac9a8724.png)

3.  [*Third Step*]
STUDY --> Plot channel measures --> Select all channels to plot and ask for spectra and...

![image](https://user-images.githubusercontent.com/52161904/90725150-0002c080-e2c0-11ea-8f4e-95e4c8908b43.png)

**Hypotheses**
I suspect the error is coming from the fact that my resting-state datasets only have 1 trial/epoch while this seems to be problematic when computing 'psd'.
Indeed, the error disappears when using 'fft' instead but another one comes up:

![image](https://user-images.githubusercontent.com/52161904/90726662-5c66df80-e2c2-11ea-85f1-0bac99a7fc18.png)

**Code to reproduce the error**
```
[STUDY ALLEEG] = pop_loadstudy('filename', 'Study_example.study', 'filepath', 'E:\Dropbox\DOC3\MATLABTests\EXAMPLE');

[STUDY ALLEEG] = std_precomp(STUDY, ALLEEG,'channels','spec','on','recompute','on',...
    'specparams',{'specmode','psd','logtrials','off'});

[STUDY,SpectData,SpectFreqs] =  std_readdata (STUDY, ALLEEG,'channels',...
    {ALLEEG(1).chanlocs.labels},'datatype','spec');

This code was nicely working with EEGLAB 14.1.2b (though I used std_readspec instead of std_readdata) but now crashes with EEGLAB2020.
```

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Windows 10 Enterprise build 17763 |
| Matlab version | Matlab R2019b |
| EEGLAB version | EEGLAB v2020.0 |

**Comment by CorentinWicht** [comment] 2020-08-20 07:14
Actually when using the code provided abobve and changing 'specmode', 'psd' to 'specmode','fft',

the following error is returned by std_readdata:

```
Unable to perform assignment because the size of the left side is 48-by-833 and the size of the right side is 48-by-833-by-1-by-64.

Error in std_readdata>reorganizedata (line 335)
                    case 3, datavals{iItem}(:,:,count:count+numItems-1) = dataTmp{iCase}{iItem};

Error in std_readdata (line 308)
datavals = reorganizedata(dataTmp, dim);
```

Hence, the problem is not solved by chaging the specmode...

**Comment by arnodelorme** [comment] 2020-08-20 16:36
First error I was not able to reproduce. I followed the instructions. Would you mind to try with the development version of EEGLAB on Github?

<img width="556" alt="Screen Shot 2020-08-20 at 6 31 57 AM" src="https://user-images.githubusercontent.com/1872705/90799586-2409d600-e2af-11ea-867e-7ef69616ff02.png">

**Comment by arnodelorme** [comment] 2020-08-20 17:29
Hi Corentin, I have fixed the PSD option as well on Github. It is returning virtually identical results compared to FFT (which makes sense) - right is PSD and left is FFT. We will need to figure out why the scale is offset though. I will close this report and submit a new one.

<img width="800" alt="Screen Shot 2020-08-20 at 7 20 04 AM" src="https://user-images.githubusercontent.com/1872705/90805023-c37e9700-e2b6-11ea-90d0-f8994e396c64.png">

**Closed as completed by arnodelorme** 2020-08-20 17:29 UTC

**Comment by Naba1210** [comment] 2022-10-25 14:42
Description
Dear EEGLAB,

I am writting here to report a bug related to the std_stdcond function (also in the GUI).

Study location: https://drive.google.com/drive/u/2/folders/0ALSJMw_UHlf9Uk9PVA
#### Steps to Reproduce
[First Step]
STUDY-->Run ICA-->Head Model and fitting-->Component Dipole autofit-->DIPFIT<15%

[Second Step]
STUDY --> Precompute component measures --> 
![2](https://user-images.githubusercontent.com/74348971/197799390-63165221-176e-4b71-999c-cb94ec4ffe8d.jpg)

[Third Step]
STUDY -->Pre clustering
![3](https://user-images.githubusercontent.com/74348971/197799703-d88660db-8604-4f03-8f63-75ada5f30ef1.jpg)

Hypotheses
I suspect that the data structure has similar events but there are some files which are showing uevents "[]"
The original files are all having same data structure, but turns out after precomputing this was the only difference i could find
![1](https://user-images.githubusercontent.com/74348971/197799954-80c59b5b-32ed-4de7-945d-c052ebf3d65d.jpg)

Code to reproduce the error

val =
    'STUDY = [];
     [STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
     [STUDY ALLEEG] = std_editset( STUDY, ALLEEG, 'name','Objective 1 ERSP','commands',{{'index' 1 'subject' 'S1'} {'index' 2 'subject' 'S2'} {'index' 3 'subject' 'S3'} {'index' 4 'subject' 'S4'} {'index' 5 'subject' 'S5'} {'index' 6 'subject' 'S6'} {'index' 7 'subject' 'S7'} {'index' 8 'subject' 'S8'} {'index' 9 'subject' 'S9'} {'index' 10 'subject' 'S10'} {'index' 1 'condition' 'B1'} {'index' 2 'condition' 'B1'} {'index' 3 'condition' 'B1'} {'index' 4 'condition' 'B1'} {'index' 5 'condition' 'B1'} {'index' 6 'condition' 'B1'} {'index' 7 'condition' 'B1'} {'index' 8 'condition' 'B1'} {'index' 9 'condition' 'B1'} {'index' 10 'condition' 'B1'} {'index' 1 'group' 'a'} {'index' 2 'group' 'a'} {'index' 3 'group' 'a'} {'index' 4 'group' 'a'} {'index' 5 'group' 'a'} {'index' 6 'group' 'a'} {'index' 7 'group' 'a'} {'index' 8 'group' 'a'} {'index' 10 'group' 'a'} {'index' 9 'group' 'a'} {'index' 11 'subject' 'S11'} {'index' 12 'subject' 'S12'} {'index' 13 'subject' 'S13'} {'index' 14 'subject' 'S14'} {'index' 15 'subject' 'S15'} {'index' 16 'subject' 'S16'} {'index' 17 'subject' 'S17'} {'index' 18 'subject' 'S18'} {'index' 19 'subject' 'S19'} {'index' 20 'subject' 'S20'} {'index' 11 'condition' 'B1'} {'index' 12 'condition' 'B1'} {'index' 13 'condition' 'B1'} {'index' 14 'condition' 'B1'} {'index' 15 'condition' 'B1'} {'index' 16 'condition' 'B1'} {'index' 17 'condition' 'B1'} {'index' 18 'condition' 'B1'} {'index' 19 'condition' 'B1'} {'index' 20 'condition' 'B1'} {'index' 11 'group' 'a'} {'index' 12 'group' 'a'} {'index' 13 'group' 'a'} {'index' 14 'group' 'a'} {'index' 15 'group' 'a'} {'index' 16 'group' 'a'} {'index' 17 'group' 'a'} {'index' 18 'group' 'a'} {'index' 19 'group' 'a'} {'index' 20 'group' 'a'} {'index' 21 'subject' 'S21'} {'index' 22 'subject' 'S22'} {'index' 23 'subject' 'S23'} {'index' 24 'subject' 'S24'} {'index' 25 'subject' 'S25'} {'index' 26 'subject' 'S26'} {'index' 27 'subject' 'S27'} {'index' 28 'subject' 'S28'} {'index' 29 'subject' 'S29'} {'index' 30 'subject' 'S30'} {'index' 21 'condition' 'B1'} {'index' 22 'condition' 'B1'} {'index' 23 'condition' 'B1'} {'index' 24 'condition' 'B1'} {'index' 25 'condition' 'B1'} {'index' 26 'condition' 'B1'} {'index' 27 'condition' 'B1'} {'index' 28 'condition' 'B1'} {'index' 29 'condition' 'B1'} {'index' 30 'condition' 'B1'} {'index' 21 'group' 'a'} {'index' 22 'group' 'a'} {'index' 23 'group' 'a'} {'index' 24 'group' 'a'} {'index' 25 'group' 'a'} {'index' 26 'group' 'a'} {'index' 27 'group' 'a'} {'index' 28 'group' 'a'} {'index' 29 'group' 'a'} {'index' 30 'group' 'a'} {'index' 31 'subject' 'S31'} {'index' 32 'subject' 'S32'} {'index' 33 'subject' 'S33'} {'index' 34 'subject' 'S34'} {'index' 35 'subject' 'S35'} {'index' 36 'subject' 'S36'} {'index' 37 'subject' 'S37'} {'index' 38 'subject' 'S38'} {'index' 39 'subject' 'S39'} {'index' 40 'subject' 'S40'} {'index' 31 'condition' 'B1'} {'index' 32 'condition' 'B1'} {'index' 33 'condition' 'B1'} {'index' 34 'condition' 'B1'} {'index' 35 'condition' 'B1'} {'index' 36 'condition' 'B1'} {'index' 37 'condition' 'B1'} {'index' 38 'condition' 'B1'} {'index' 39 'condition' 'B1'} {'index' 40 'condition' 'B1'} {'index' 31 'group' 'a'} {'index' 32 'group' 'a'} {'index' 33 'group' 'a'} {'index' 34 'group' 'a'} {'index' 35 'group' 'a'} {'index' 36 'group' 'a'} {'index' 37 'group' 'a'} {'index' 38 'group' 'a'} {'index' 39 'group' 'a'} {'index' 40 'group' 'a'} {'index' 41 'subject' 'S1'} {'index' 42 'subject' 'S2'} {'index' 43 'subject' 'S3'} {'index' 44 'subject' 'S4'} {'index' 45 'subject' 'S5'} {'index' 46 'subject' 'S6'} {'index' 47 'subject' 'S7'} {'index' 48 'subject' 'S8'} {'index' 49 'subject' 'S9'} {'index' 50 'subject' 'S10'} {'index' 41 'condition' 'B2'} {'index' 42 'condition' 'B2'} {'index' 43 'condition' 'B2'} {'index' 44 'condition' 'B2'} {'index' 45 'condition' 'B2'} {'index' 46 'condition' 'B2'} {'index' 47 'condition' 'B2'} {'index' 48 'condition' 'B2'} {'index' 49 'condition' 'B2'} {'index' 50 'condition' 'B2'} {'index' 41 'group' 'a'} {'index' 42 'group' 'a'} {'index' 43 'group' 'a'} {'index' 44 'group' 'a'} {'index' 45 'group' 'a'} {'index' 46 'group' 'a'} {'index' 47 'group' 'a'} {'index' 48 'group' 'a'} {'index' 49 'group' 'a'} {'index' 50 'group' 'a'} {'index' 51 'condition' 'B2'} {'index' 52 'condition' 'B2'} {'index' 53 'condition' 'B2'} {'index' 54 'condition' 'B2'} {'index' 55 'condition' 'B2'} {'index' 56 'condition' 'B2'} {'index' 57 'condition' 'B2'} {'index' 58 'condition' 'B2'} {'index' 59 'condition' 'B2'} {'index' 60 'condition' 'B2'} {'index' 51 'subject' 'S11'} {'index' 52 'subject' 'S12'} {'index' 53 'subject' 'S13'} {'index' 54 'subject' 'S14'} {'index' 55 'subject' 'S15'} {'index' 56 'subject' 'S16'} {'index' 57 'subject' 'S17'} {'index' 58 'subject' 'S18'} {'index' 59 'subject' 'S19'} {'index' 60 'subject' 'S20'} {'index' 51 'group' 'a'} {'index' 52 'group' 'a'} {'index' 53 'group' 'a'} {'index' 54 'group' 'a'} {'index' 55 'group' 'a'} {'index' 56 'group' 'a'} {'index' 57 'group' 'a'} {'index' 58 'group' 'a' 'group' 'a'} {'index' 59 'group' 'a'} {'index' 60 'group' 'a'} {'index' 61 'subject' 'S21'} {'index' 62 'subject' 'S22'} {'index' 63 'subject' 'S23'} {'index' 64 'subject' 'S24'} {'index' 65 'subject' 'S25'} {'index' 66 'subject' 'S26'} {'index' 67 'subject' 'S27'} {'index' 68 'subject' 'S28'} {'index' 69 'subject' 'S29'} {'index' 70 'subject' 'S30'} {'index' 61 'condition' 'B2'} {'index' 62 'condition' 'B2'} {'index' 63 'condition' 'B2'} {'index' 64 'condition' 'B2'} {'index' 65 'condition' 'B2'} {'index' 66 'condition' 'B2'} {'index' 67 'condition' 'B2'} {'index' 68 'condition' 'B2'} {'index' 69 'condition' 'B2'} {'index' 70 'condition' 'B2'} {'index' 61 'group' 'a'} {'index' 62 'group' 'a'} {'index' 63 'group' 'a'} {'index' 64 'group' 'a'} {'index' 65 'group' 'a'} {'index' 66 'group' 'a'} {'index' 67 'group' 'a'} {'index' 68 'group' 'a'} {'index' 69 'group' 'a'} {'index' 70 'group' 'a'} {'index' 71 'group' 'a'} {'index' 72 'group' 'a'} {'index' 73 'group' 'a'} {'index' 74 'group' 'a'} {'index' 75 'group' 'a'} {'index' 76 'group' 'a'} {'index' 77 'group' 'a'} {'index' 78 'group' 'a'} {'index' 79 'group' 'a'} {'index' 80 'group' 'a'} {'index' 71 'condition' 'B2'} {'index' 72 'condition' 'B2'} {'index' 73 'condition' 'B2'} {'index' 74 'condition' 'B2'} {'index' 75 'condition' 'B2'} {'index' 76 'condition' 'B2'} {'index' 77 'condition' 'B2'} {'index' 78 'condition' 'B2'} {'index' 79 'condition' 'B2'} {'index' 80 'condition' 'B2'} {'index' 71 'subject' 'S31'} {'index' 72 'subject' 'S32'} {'index' 73 'subject' 'S33'} {'index' 74 'subject' 'S34'} {'index' 75 'subject' 'S35'} {'index' 76 'subject' 'S36'} {'index' 77 'subject' 'S37'} {'index' 78 'subject' 'S38'} {'index' 79 'subject' 'S39'} {'index' 80 'subject' 'S40'} {'index' 81 'condition' 'B3'} {'index' 82 'condition' 'B3'} {'index' 83 'condition' 'B3'} {'index' 84 'condition' 'B3'} {'index' 85 'condition' 'B3'} {'index' 87 'condition' 'B3'} {'index' 86 'condition' 'B3'} {'index' 88 'condition' 'B3'} {'index' 89 'condition' 'B3'} {'index' 90 'condition' 'B3'} {'index' 81 'subject' 'S1'} {'index' 82 'subject' 'S2'} {'index' 83 'subject' 'S3'} {'index' 84 'subject' 'S4'} {'index' 85 'subject' 'S5'} {'index' 86 'subject' 'S6'} {'index' 87 'subject' 'S7'} {'index' 88 'subject' 'S8'} {'index' 89 'subject' 'S9'} {'index' 90 'subject' 'S10'} {'index' 81 'group' 'a'} {'index' 82 'group' 'a'} {'index' 83 'group' 'a'} {'index' 84 'group' 'a'} {'index' 85 'group' 'a'} {'index' 86 'group' 'a'} {'index' 87 'group' 'a'} {'index' 88 'group' 'a'} {'index' 89 'group' 'a'} {'index' 90 'group' 'a'} {'index' 91 'subject' 'S11'} {'index' 92 'subject' 'S12'} {'index' 93 'subject' 'S13'} {'index' 94 'subject' 'S14'} {'index' 95 'subject' 'S15'} {'index' 96 'subject' 'S16'} {'index' 97 'subject' 'S17'} {'index' 98 'subject' 'S18'} {'index' 99 'subject' 'S19'} {'index' 100 'subject' 'S20'} {'index' 91 'condition' 'B3'} {'index' 92 'condition' 'B3'} {'index' 93 'condition' 'B3'} {'index' 94 'condition' 'B3'} {'index' 95 'condition' 'B3'} {'index' 96 'condition' 'B3'} {'index' 97 'condition' 'B3'} {'index' 98 'condition' 'B3'} {'index' 99 'condition' 'B3'} {'index' 100 'condition' 'B3'} {'index' 91 'group' 'a'} {'index' 92 'group' 'a'} {'index' 93 'group' 'a'} {'index' 94 'group' 'a'} {'index' 95 'group' 'a'} {'index' 96 'group' 'a'} {'index' 97 'group' 'a'} {'index' 98 'group' 'a'} {'index' 99 'group' 'a'} {'index' 100 'group' 'a'} {'index' 101 'subject' 'S21'} {'index' 102 'subject' 'S22'} {'index' 103 'subject' 'S23'} {'index' 104 'subject' 'S24'} {'index' 105 'subject' 'S25'} {'index' 106 'subject' 'S26'} {'index' 107 'subject' 'S27'} {'index' 108 'subject' 'S28'} {'index' 109 'subject' 'S29'} {'index' 110 'subject' 'S30'} {'index' 101 'condition' 'B3'} {'index' 102 'condition' 'B3'} {'index' 103 'condition' 'B3'} {'index' 104 'condition' 'B3'} {'index' 105 'condition' 'B3'} {'index' 106 'condition' 'B3'} {'index' 107 'condition' 'B3'} {'index' 108 'condition' 'B3'} {'index' 109 'condition' 'B3'} {'index' 110 'condition' 'B3'} {'index' 101 'group' 'a'} {'index' 102 'group' 'a'} {'index' 103 'group' 'a'} {'index' 104 'group' 'a'} {'index' 105 'group' 'a'} {'index' 107 'group' 'a'} {'index' 106 'group' 'a'} {'index' 108 'group' 'a'} {'index' 109 'group' 'a'} {'index' 110 'group' 'a'} {'index' 111 'subject' 'S31'} {'index' 112 'subject' 'S32'} {'index' 113 'subject' 'S33'} {'index' 114 'subject' 'S34'} {'index' 115 'subject' 'S35'} {'index' 116 'subject' 'S36'} {'index' 117 'subject' 'S37'} {'index' 118 'subject' 'S38'} {'index' 119 'subject' 'S39'} {'index' 120 'subject' 'S40'} {'index' 112 'condition' 'B3'} {'index' 111 'condition' 'B3'} {'index' 113 'condition' 'B3'} {'index' 114 'condition' 'B3'} {'index' 115 'condition' 'B3'} {'index' 116 'condition' 'B3'} {'index' 117 'condition' 'B3'} {'index' 118 'condition' 'B3'} {'index' 119 'condition' 'B3'} {'index' 120 'condition' 'B3'} {'index' 111 'group' 'a'} {'index' 112 'group' 'a'} {'index' 113 'group' 'a'} {'index' 114 'group' 'a'} {'index' 115 'group' 'a'} {'index' 116 'group' 'a'} {'index' 117 'group' 'a'} {'index' 118 'group' 'a'} {'index' 119 'group' 'a'} {'index' 120 'group' 'a'} {'remove' 121} {'index' 50 'load' 'D:\\Block 2\\Sub7_Gp1_Blk2.set' 'subject' 'S10' 'condition' 'B2' 'group' 'a'}},'updatedat','on','savedat','on','rmclust','on' );
     [STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
     STUDY = std_makedesign(STUDY, ALLEEG, 1, 'variable1','condition','variable2','condition','name','STUDY.design 1','pairing1','on','pairing2','on','delfiles','off','defaultdesign','off','values1',{'B1' 'B2'},'values2',{'B2' 'B3'},'subjselect',{'S1' 'S10' 'S11' 'S12' 'S13' 'S14' 'S15' 'S16' 'S17' 'S18' 'S19' 'S2' 'S20' 'S21' 'S22' 'S23' 'S24' 'S25' 'S26' 'S27' 'S28' 'S29' 'S3' 'S30' 'S31' 'S32' 'S33' 'S34' 'S35' 'S36' 'S37' 'S38' 'S39' 'S4' 'S40' 'S5' 'S6' 'S7' 'S8' 'S9'});
     
     [STUDY EEG] = pop_savestudy( STUDY, EEG, 'filename','Objective 1.study','filepath','D:\\');
     [STUDY EEG] = pop_savestudy( STUDY, ALLEEG, 'savemode','resave');
     [STUDY EEG] = pop_savestudy( STUDY, EEG, 'savemode','resave');
     [STUDY EEG] = pop_savestudy( STUDY, ALLEEG, 'savemode','resave');
     [STUDY EEG] = pop_savestudy( STUDY, EEG, 'savemode','resave');
     [STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
     [STUDY ALLEEG] = std_editset( STUDY, ALLEEG, 'commands',{{'inbrain' 'on' 'dipselect' 0.15}},'updatedat','on','savedat','on','rmclust','on' );
     [STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
     [STUDY ALLEEG] = std_precomp(STUDY, ALLEEG, 'components','recompute','on','scalp','on','spec','on','specparams',{'specmode' 'fft' 'logtrials' 'off'},'ersp','on','erspparams',{'cycles' [3 0.8]  'nfreqs' 100 'ntimesout' 200},'itc','on');
     [STUDY ALLEEG] = std_preclust(STUDY, ALLEEG, 1,{'spec' 'npca' 10 'norm' 1 'weight' 1 'freqrange' [1 25] },{'scalp' 'npca' 10 'norm' 1 'weight' 1 'abso' 1},{'dipoles' 'norm' 1 'weight' 10},{'ersp' 'npca' 10 'freqrange' [] 'timewindow' [] 'norm' 1 'weight' 1},{'itc' 'npca' 10 'freqrange' [] 'timewindow' [] 'norm' 1 'weight' 1},{'finaldim' 'npca' 10});
     [STUDY] = pop_clust(STUDY, ALLEEG, 'algorithm','kmeans','clus_num',  10 , 'outliers',  3 );
     STUDY = std_erspplot(STUDY,ALLEEG,'clusters',3, 'plotsubjects', 'on' );
     STUDY = pop_statparams(STUDY, 'condstats','on','method','perm','mcorrect','fdr');
     STUDY = pop_erspparams(STUDY, 'topotime',NaN,'topofreq',NaN,'timerange',[0 2000] ,'freqrange',[1 25] );
     STUDY = pop_erspparams(STUDY, 'topotime',NaN,'topofreq',NaN,'freqrange',[]);
     [STUDY EEG] = pop_savestudy( STUDY, EEG, 'savemode','resave');
     [STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
     [STUDY ALLEEG] = pop_loadstudy('filename', 'Objective 1.study', 'filepath', 'D:\');'

ERROR: Number of elements must not change. Use [] as one of the size inputs to automatically calculate the appropriate size for that dimension.
