### ISSUE TITLE
edit->channel locations: from .elp file #538; same problem with EEGlab2023,1

### ISSUE THREAD

**Issue by kwswan** [eeglabdevelopers/eeglab#703] opened 2023-11-21 15:56 UTC
I had a very similar issue previously, solved under issue #538, but now it happens also with EEGlab 2023.1
When changing the channel locations in older versions of eeglab, the attached .elp file works fine for 128 channel biosemi data. 
With 2023.1 I can read the locations via the gui using autodetect. But when I therafter click on Plot 2-D I get error messages in matlab (see screenshot) which show that something likely did not go well when reading in the .elp file.

attached is also the .elp file we are using (to enable upload, this file is here a .txt file, in reality, the file has the extension .elp) . Any suggestion would be appreciated.

[coords3.txt](https://github.com/sccn/eeglab/files/13428323/coords3.txt)
![MatlabErrors](https://github.com/sccn/eeglab/assets/114073190/80345ad4-2da0-4acd-b073-f63ccc3c9983)

**Comment by arnodelorme** [comment] 2024-02-08 05:27
Are you using the latest version of EEGLAB. I could not reproduce the problems. This is the history after I tried from the GUI.
Can you try running this script. This works for me.

```matlab
eeglab
a = rand(130, 100,100);
EEG = pop_importdata('dataformat','array','nbchan',0,'data','a','srate',100,'pnts',0,'xmin',0);
EEG=pop_chanedit(EEG, 'load',{'/Users/arno/temp/coords3.txt','filetype','besa'});
```
![Screenshot 2024-02-07 at 9 25 55 PM](https://github.com/sccn/eeglab/assets/1872705/2e29772c-62bf-4788-835d-567d68cbf657)

Also attaching the plotted channel locations.

**Comment by arnodelorme** [comment] 2024-02-08 05:28
Closing for now, but feel free to reopen.

**Closed as completed by arnodelorme** 2024-02-08 05:28 UTC
