### ISSUE TITLE
Some XDF files channels lost and frequency changed after imported

### ISSUE THREAD

**Issue by Mermaidlegs** [eeglabdevelopers/eeglab#254] opened 2021-02-03 13:28 UTC
### There are two problems I faced when using xdf import plugin 1.18

<br>
#### Steps to Reproduce

1. Import the xdf files by using xdf file import function
2. Some of the datasets are opened with 256 hz and 16 channels (right sampling rate and right numbers of the channels)
3. However, some of the datasets are opened with 1000 hz and 1 channel only
notes: we are sure that every dataset was recorded with the same paramteres and the same sampling rate

Please see the drive link for more details.

<br>
#### Expected behaviour:
all the datasets would be opened with the right sampling rate and right numbers of channels.

|   |   |
|----| ---- | 
| OS version     | [10.15.3] |
| Matlab version | [R2020b] |
| EEGLAB version | [2020.0] |

Thank you so much for the help and support.

**Comment by Mermaidlegs** [comment] 2021-02-03 13:36
https://drive.google.com/drive/folders/1IALV3LAI1jUOM3pnatZcNwSwXnH6w6cC?usp=sharing

The link is here.

Thank you in advance.

**Comment by cll008** [comment] 2021-05-07 17:00
Hi @Mermaidlegs, thanks for the clear documentation on your google drive. Are you still running into this issue? 
I took a quick look and it seems the problem is with the recording settings rather than EEGLAB import function. In the sample data you sent, the dataset with 1 channel and 1000 Hz is from an ECG channel. Is it possible that the wrong subset of channels were recorded?

**Comment by cll008** [comment] 2021-05-10 23:14
I'll close this for now but please reopen if necessary. Thanks.

**Closed as completed by cll008** 2021-05-10 23:14 UTC
